name:                tau
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/tau#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.2.1 && < 0.7.0.0
  - deriving-compat >= 0.5.9 && < 1.0.0
  - set-monad >= 0.3.0 && < 1.0.0
  - recursion-schemes >= 5.1.3 && < 6.0.0
  - mtl >= 2.2.2 && < 3.0.0
  - text >= 1.2.4.0 && < 1.3.0.0

library:
  source-dirs: 
    - src/
    - monad-supply/src/

executables:
  tau:
    source-dirs:      app/
    main:             Main.hs
    dependencies:
    - tau

tests:
  tau-test:
    source-dirs:      test/
    main:             Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - tau
