name:                tau
version:             0.1.0.0
github:              "githubuser/tau"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"
extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tau#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- data-fix
- deriving-compat
- extra
- megaparsec
- mtl
- parser-combinators
- recursion-schemes
- set-monad
- text
- text-show
- transformers
- monad-supply

library:
  source-dirs: src

executables:
  tau-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tau

tests:
  tau-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tau
    - hspec
