name:                tau
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/temp#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2020 Author name here
category:            Tau
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - deriving-compat
  - extra
  - megaparsec
  - mtl
  - parser-combinators
  - prettyprinter
  - recursion-schemes
  - repline
  - set-monad
  - text
  - transformers

library:
  source-dirs: 
    - src/
    - monad-supply/src/
  ghc-options:
    - -Wall

executables:
  temp:
    source-dirs:      app/
    main:             Main.hs
    # ghc-options:
      #- -Wall
    dependencies:
    - tau

tests:
  tau-test:
    source-dirs:      
    - test/
    - src/
    main:             Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
      #- -Wall
    dependencies:
    - tau
    - hspec
