name:                tau
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/tau#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- data-fix
- deriving-compat
- either
- extra
- free
- megaparsec
- monad-supply
- mtl
- parser-combinators
- prettyprinter
- recursion-schemes
- repline
- set-monad
- text
- transformers
- tree-view
- type-iso

library:
  source-dirs: src

executables:
  tau-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tau

tests:
  tau-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tau
