name:                a-simple-toy-language
version:             0.1.0.0
#synopsis:
#description:
#homepage:            
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text >= 1.2.3.1 && < 1.3.0.0
  - mtl >= 2.2.2 && < 2.3.0
  - containers >= 0.6.0.1 && < 0.7.0.0
  - megaparsec >= 7.0.5 && < 7.1.0
  - parser-combinators >= 1.1.0 && < 1.2.0

executables:
  proto1:
    source-dirs:      src
    main:             Main.hs
